---
- name: Get GitHub SSH keys
  local_action: get_url url="https://github.com/{{ item.username }}.keys" dest="/tmp/{{ item.username }}.keys"
  sudo: false
  with_items: github_ssh_keys

- name: Add SSH keys
  authorized_key: user="{{ item.1 }}" key="{{ lookup('file', '/tmp/' + item.0.username + '.keys') }}"
  with_subelements:
     - github_ssh_keys | default([])
     - authorized
